[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "salary-forecast"
version = "0.1.0"
description = "A salary forecasting engine."
readme = "README.md"
authors = [
    { name = "Jonathan", email = "jonkmatsumo@gmail.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    "xgboost>=2.0.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0",
    "optuna>=3.0.0",
    "streamlit>=1.28.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "mlflow>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
salary-forecast-train = "src.cli.train_cli:main"
salary-forecast-infer = "src.cli.inference_cli:main"
salary-forecast-config = "src.cli.generate_config_cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "."
addopts = "-v"
